YEL-1281
UKHomeOffice/dq-packer-ext-tableau pull request #9
Opened 2018-11-08 15:43 UTC by ianrelf

2018-11-08 15:45 UTC, duncan9562 approved these changes
LGTM

2018-11-09 07:36 UTC, david-wirelab requested changes

2018-11-09 07:36 UTC, david-wirelab commented on playbook.yml
> -    - name: Convert line endings from Linux to Windows (PowerShell)
I think the partitioning task needs to stay.

2018-11-09 08:25 UTC, ianrelf commented on playbook.yml
> -    - name: Convert line endings from Linux to Windows (PowerShell)
I no longer even pull the `partitioning.txt` file into the AMI.
The Tableau AMI now specifies a single 1TB C-Drive, rather than 2x 500GB C & D-Drives.
The Instances appear to have the full 1TB available so I don't think that the partitioning is required.

2018-11-09 10:15 UTC, david-wirelab approved these changes
LGTM

2018-11-09 10:21 UTC, merged